<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<NeutralLanguage>ru</NeutralLanguage>

		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<DocumentationFile>LibPsqlDocs.xml</DocumentationFile>
		<NoWarn>1591;1573</NoWarn>

		<Version>10.2.0</Version>
		<VersionPrefix>$(Version)</VersionPrefix>
		<Authors>Roman Koff</Authors>
		<Copyright>$(Authors)</Copyright>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.12" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Ans.Net10.Common\Ans.Net10.Common.csproj" />
	</ItemGroup>

</Project>
